#! /bin/sh

# Check to make sure we've received an argument
if [ $# -eq 0 ]; then
	echo "Usage: runcpp <source-file.cpp>"
	exit 1
fi

CPPFILE=$1
OUTFILE=${CPPFILE%.cpp}

echo "Compiling ${CPPFILE} with gcc..."

# Try to compile the source code
if g++ -std=c++17 -fconcepts ${CPPFILE} -o ${OUTFILE}; then

	# The source code compiled
	echo "Successfully complied."
	echo "Running executable file ${OUTFILE}..."
	# Run the executable
	./${OUTFILE}

else
	
	echo "Failed to compile, exit status: $?"

fi
